version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: docarise-redis
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    command: redis-server --port ${REDIS_PORT} --dir /data --appendonly yes
    volumes:
      - docarise-redis-data:/data

  postgres:
    image: postgres:16-alpine
    container_name: docarise-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - docarise-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1 -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  docarise-redis-data: {}
  docarise-postgres-data: {}
